### ISSUE TITLE
feat: support fish

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/cli_completion#11]
**Description**

Support fish terminal

**Requirements**

- [ ] Support fish for where possible

**Additional Context**

Extracted from #1 the included fish at first

**Comment by tomarra** [comment]
Open for almost a year and no upvotes on this. Closing this out as "Won't Fix"

**Comment by vanyasem** [comment]
@tomarra Upvoted

**Comment by tomarra** [comment]
Hi @vanyasem, thanks for the comment. There doesn't seem to be much community interest in this feature overall so I'm going to keep the ticket closed. 

That being said if this is something you would be willing to help out and contribute back to the package I'm sure I can find some cycles from the VGV team to review a PR with the functionality.
