### ISSUE TITLE
Completions are slow to appear

### ISSUE THREAD

**Issue by bartekpacia** [VeryGoodOpenSource/cli_completion#62]
**Description**

Upon pressing `tab`, the completions take about ~500ms to load. This greatly reduces the experience.

Am I the only one experiencing this? What can be potentially causing this low performance? (I suspect some Dart program is run on every `tab` to recalculate completions? IDK honestly, didn't have time to dig in code of this (otherwise awesome) package).

I'm on the latest macOS Ventura, using `zsh 5.9` with `ohmyzsh`, FWIW.

PS Sorry for not following the issue template.

**Comment by renancaraujo** [comment]
So, a little of clarification on how completions work: when the user press tab, the shell scripts that are generated from [this template](https://github.com/VeryGoodOpenSource/cli_completion/blob/main/lib/src/installer/shell_completion_configuration.dart#L71) runs a `completion` subcommand in your CLI. So this command runs and whatever it pops out to stdout will be interpreted as suggestions for the user to pick.

This takes longer if you do common operations on all commands, that is why people should fast track the `completion` command on the command runner subclass and skip anything that may slow it down such as:
- analytics
- checking for updates

Thers is a hint on how to do this on [the readme](https://github.com/VeryGoodOpenSource/cli_completion#%EF%B8%8F-using-analytics):

> Handling completion requests should be straightforward. If there are any checks (like analytics, telemetry, or anything that you may have on `run` or `runCommand` overrides) before running subcommands, make sure you fast track the `completion` command to skip all of the unnecessary computations.





> PS Sorry for not following the issue template.

I will allow it this time.

**Comment by renancaraujo** [comment]
@bartekpacia is there anything else I can help you with? or should we close this issue?

**Comment by bartekpacia** [comment]
The cause of my problem was indeed slow code on the critical path:

https://github.com/leancodepl/patrol/issues/1966
