### ISSUE TITLE
fix: The package touches files and directories in `$HOME` without asking

### ISSUE THREAD

**Issue by bartekpacia** [VeryGoodOpenSource/cli_completion#64]
**Description**

When my CLI program (that is using `package:cli_completion`) is run for the first time, it:
- appends some initialization logic to `~/.zshrc` (in my case - I'm using Zsh)

    ```console
    $ tail -n 5 ~/.zshrc                                                                                      
    ## [Completion]
    ## Completion scripts setup. Remove the following line to uninstall
    [[ -f /Users/bartek/.config/.dart-cli-completion/zsh-config.zsh ]] && . /Users/bartek/.config/.dart-cli-completion/zsh-config.zsh || true
    ## [/Completion]
    ```

- creates the `~/.dart-cli-completion` directory, which apparently stores the completion files for every program using it:
    
    ```console
    $ ls ~/.dart-cli-completion/
    patrol.zsh     zsh-config.zs
    ```

**Steps To Reproduce**

Add this package to a CLI program (as per the README) and run it.

**Expected Behavior**

I don't want my CLI program to touch my user's `$HOME`. It's not nice.

I also feel like this behavior should be clearly stated in the readme. 

**Additional Context**

Initially reported [in this issue](https://github.com/leancodepl/patrol/issues/1225).

**Comment by renancaraujo** [comment]
Hell there,

As the docs say, to disable auto install, set 'enableAutoInstall' to false on your CompletionCommandRunner subclass. 

The workings of the package are stated in the docs:

https://github.com/VeryGoodOpenSource/cli_completion/tree/main/doc

**Comment by bartekpacia** [comment]
Thanks for the quick answer.

I have no experience with shell completions, but could an alternative approach be developed? Some software automatically installs its own completions when `brew install`ed.

Though I suspect that it'd be more complicated to set up than it currently is.

**Comment by renancaraujo** [comment]
There are other ways, for example, fig. But that requires the completion schema to be published within its registry, with is not too ergonomic. 
Another alternative is to add completions in runtime via oh my zsh plugin system. 

Any of these alternatives rule out the possibility of mapping the suggestions from the `ArgParser` objects, which is the whole point of this package.

For this issue, we can:

- Disable auto-install by default, or
- Remove auto-install altogether and force final users to install scripts "manually"

**Comment by bartekpacia** [comment]
> Disable auto-install by default

I wouldn't do it. I might not like scripts modifying my `~/.zshrc` but I'm sure a whole lot more people don't bother with it, but they do want to have completions.

> Remove auto-install altogether and force final users to install scripts "manually"

Could there be 2 ways of installing the completions? The current one - automatic, and the new one - manual - that'd require the user to move the generated completions file into [<some place where all completion files live>](https://unix.stackexchange.com/questions/607809/where-should-i-install-the-zsh-completion-file-as-a-package-maintainer).

**Comment by bartekpacia** [comment]
I am going to close this issue since my question has been answered [here](https://github.com/VeryGoodOpenSource/cli_completion/issues/64#issuecomment-1522182903). Thank you!
